In [1]:
import numpy as np
import matplotlib.pyplot as plt

Initializing needed parameters.

In [2]:
V52diameter = 52
V52height = 44  # hub height

V27diameter = 27
V27height = 31.5 # hub height

mast_height = V52height

V52position = np.array([317548, 6174985])
V27position = np.array([317519, 6174901])
mast_position = np.array([317438, 6175028])

Reference measurements to state whether an obstacle is relevant or not

In [3]:
(V52height - V52diameter) * 2 / 3 # reference to see if a nearby operating WT is small
def calculate_distance_coordinates(coord1, coord2):
    return np.sqrt((coord2[0] - coord1[0]) ** 2 + (coord2[1] - coord1[1]) ** 2)

L1 = calculate_distance_coordinates(V52position, mast_position) # distance between the mast and the V52
L2 = calculate_distance_coordinates(V27position, mast_position) # distance between the mast and the V27
L3 = calculate_distance_coordinates(V27position, V52position) # distance between the WTs
L1, L2, L3


(118.10588469674151, 150.63200191194434, 88.86506625215557)

Azimuthal positions with respect to North

In [4]:
dir1 = np.degrees(np.arctan((np.abs(V52position[1] - mast_position[1])) / (np.abs(V52position[0] - mast_position[0])))) + 90 # direction from the mast to the V52
dir2 = np.degrees(np.arctan((np.abs(V27position[1] - mast_position[1])) / (np.abs(V27position[0] - mast_position[0])))) + 90  # direction from the mast to the V27
dir3 = np.degrees(np.arctan(V27position[1] - V52position[1]) / (V27position[0] - V52position[0])) + 180  # direction from the V52 to the V27
dir1, dir2, dir3

(111.3509802476536, 147.4704617216689, 183.07992895195957)

Function to calculate disturbance sectors

In [5]:
def calculate_disturbance_sector(distance, diameter): # use equivalent distance and diameter for obstacles different from a WT

    alfa = 1.3 * (np.rad2deg(np.arctan ((2.5 * diameter / distance) + 0.15))) + 10
    ratio = distance / diameter
    
    return alfa, ratio


Wake-free influence sectors

In [6]:
alfa1, ratio1 = calculate_disturbance_sector(L1, V52diameter) # disturbance sector of the V52 on the mast
alfa2, ratio2 = calculate_disturbance_sector(L2, V27diameter) # disturbance sector of the V27 on the mast
alfa3, ratio3 = calculate_disturbance_sector(L3, V27diameter) # disturbance sector of the V27 on the V52
results = {
    "V52 on mast": {"alfa": alfa1, "ratio": ratio1},
    "V27 on mast": {"alfa": alfa2, "ratio": ratio2},
    "V27 on V52": {"alfa": alfa3, "ratio": ratio3}
}
results

{'V52 on mast': {'alfa': 76.76279903096264, 'ratio': 2.2712670133988753},
 'V27 on mast': {'alfa': 50.14939254563706, 'ratio': 5.578963033775716},
 'V27 on V52': {'alfa': 64.97567826079508, 'ratio': 3.291298750079836}}

The following obstacles can be identified:
- Building 399
- Ecotron building
- Wind turbine prototype southwards
- Group of trees EN
- Woods ES

The masts in south direction (3 measurement masts) are not considered obstacles (ref Assignment 2 for reasoning).
Assumptions:
- Building heights: 399 is 8 m tall, Ecotron is 10 m tall
- WT prototype is 20 m tall 
- Trees heights are 4 m

Initialize obstacles distances (on WT V52) and heights

In [7]:
obstacles = ["trees North-East (NE)", "build. 399", "Ecotron", "trees ES", "WT prototype"]
heights = np.array([4, 8, 10, 4, 20])
distances1 = np.array([153.08, 61.38, 78.62, 214.1, 282.11]) # from V52 to, respectively: trees North-East (NE), build. 399, Ecotron, trees ES, WT prototype
distances2 = np.array([258.18, 143.19, 155, 331.32, 313.1])



Reference distances and heights 

In [8]:
ref_distance = np.array([2*L1, 4*L1, 8*L1, 16*L1])
ref_heights = np.array([
    (V52height - V52diameter/2) / 3,
    (V52height - V52diameter/2) / 3 * 2,
    (V52height - V52diameter/2),
    (V52height - V52diameter/2) * 4 / 3
])

Comparison with reference measurements to check whether obstacles can be considered irrelevant or not

In [9]:
def find_relevant_obstacles(distances):

    relevant_obstacles = []
    for i in range(len(distances)):
        if distances[i] < ref_distance[0]:
            if heights[i] >= ref_heights[0]:
                print(f"Obstacle {i} being {obstacles[i]} is relevant")
                relevant_obstacles.append(obstacles[i])
        elif distances[i] < ref_distance[1]:
            if heights[i] >= ref_heights[1]:
                print(f"Obstacle {i} being {obstacles[i]} is relevant")
                relevant_obstacles.append(obstacles[i])
        elif distances[i] < ref_distance[2]:
            if heights[i] >= ref_heights[2]:
                print(f"Obstacle {i} being {obstacles[i]} is relevant")
                relevant_obstacles.append(obstacles[i])
        elif distances[i] < ref_distance[3]:
            if heights[i] >= ref_heights[3]:
                print(f"Obstacle {i} being {obstacles[i]} is relevant")
                relevant_obstacles.append(obstacles[i])
        else:
            print(f"Obstacle {i} being {obstacles[i]} is not relevant because is further than {ref_distance[3]} m")

    return relevant_obstacles

# Relevant obstacles for V52
print("The relevant obstacles on V52 are:\n")
relevant_obstacles_V52 = find_relevant_obstacles(distances1)
#Relevant obstacles for mast
print("\nThe relevant obstacles on met mast are:\n")
relevant_obstacles_mast = find_relevant_obstacles(distances2)

The relevant obstacles on V52 are:

Obstacle 1 being build. 399 is relevant
Obstacle 2 being Ecotron is relevant
Obstacle 4 being WT prototype is relevant

The relevant obstacles on met mast are:

Obstacle 1 being build. 399 is relevant
Obstacle 2 being Ecotron is relevant
Obstacle 4 being WT prototype is relevant


Calculation of equivalent diameter for relevant obstacles, so building 399, Ecotron and WT prototype. Definition of obstacles width as seen from V52 is also implemented in this step.

In [10]:
relevant_width = np.array([15.17, 35.94, 2.28]) # respectively, widths of: building 399, Ecotron, WT prototype
eq_diameters = []

def calculate_equivalent_diameter(obs_height, obs_width):
    return 2 * obs_height * obs_width / (obs_height + obs_width)

def list_equivalent_diameters(relevant_obstacles):

    for i in range(len(relevant_obstacles)):
        if relevant_obstacles[i] == "build. 399":
            eq_diameter = calculate_equivalent_diameter(heights[1], relevant_width[0])
            print(f"Equivalent diameter of building 399: {eq_diameter} m")
            eq_diameters.append(eq_diameter)
        elif relevant_obstacles[i] == "Ecotron":
            eq_diameter = calculate_equivalent_diameter(heights[2], relevant_width[1])
            print(f"Equivalent diameter of Ecotron: {eq_diameter} m")
            eq_diameters.append(eq_diameter)
        elif relevant_obstacles[i] == "WT prototype":
            eq_diameter = calculate_equivalent_diameter(heights[4], relevant_width[2])
            print(f"Equivalent diameter of WT prototype: {eq_diameter} m")
            eq_diameters.append(eq_diameter)

    return eq_diameters

eq_diameters_V52 = list_equivalent_diameters(relevant_obstacles_V52)
eq_diameters_mast = list_equivalent_diameters(relevant_obstacles_mast)

Equivalent diameter of building 399: 10.475615019421666 m
Equivalent diameter of Ecotron: 15.6464954288202 m
Equivalent diameter of WT prototype: 4.093357271095152 m
Equivalent diameter of building 399: 10.475615019421666 m
Equivalent diameter of Ecotron: 15.6464954288202 m
Equivalent diameter of WT prototype: 4.093357271095152 m


Computation of disturbances sector due to relevant obstacles.

In [11]:
alfa4, ratio4 = calculate_disturbance_sector(distances1[1], eq_diameters_V52[0]) # disturbance sector of building 399 on V52
alfa5, ratio5 = calculate_disturbance_sector(distances1[2], eq_diameters_V52[1]) # disturbance sector of Ecotron on V52
alfa6, ratio6 = calculate_disturbance_sector(distances1[4], eq_diameters_V52[2]) # disturbance sector of WT prototype on V52
alfa7, ratio7 = calculate_disturbance_sector(distances2[1], eq_diameters_mast[0]) # disturbance sector of building 399 on mast
alfa8, ratio8 = calculate_disturbance_sector(distances2[2], eq_diameters_mast[1]) # disturbance sector of Ecotron on mast
alfa9, ratio9 = calculate_disturbance_sector(distances1[4], eq_diameters_V52[2]) # disturbance sector of WT prototype on V52

results_obstacles = {
    "building 399 on V52": {"alfa": alfa4, "ratio": ratio4},
    "Ecotron on V52": {"alfa": alfa5, "ratio": ratio5}, 
    "WT prototype on V52": {"alfa": alfa6, "ratio": ratio6},
    "building 399 on mast": {"alfa": alfa7, "ratio": ratio7},
    "Ecotron on mast": {"alfa": alfa8, "ratio": ratio8}, 
    "WT prototype on mast": {"alfa": alfa9, "ratio": ratio9},
}
results_obstacles

{'building 399 on V52': {'alfa': 48.962016671148525,
  'ratio': 5.859321852340146},
 'Ecotron on V52': {'alfa': 52.80183543734507, 'ratio': 5.024767390094603},
 'WT prototype on V52': {'alfa': 23.717350116858324,
  'ratio': 68.91897807017546},
 'building 399 on mast': {'alfa': 33.93618712163128,
  'ratio': 13.668887195121952},
 'Ecotron on mast': {'alfa': 38.49342775001993, 'ratio': 9.906371730662215},
 'WT prototype on mast': {'alfa': 23.717350116858324,
  'ratio': 68.91897807017546}}

Definition of direction angles referred to V52 turbine to compute disturbances sector of relevant obstacles on V52 (directions taken as 'heading' from Google Earth project)

In [12]:
dir4 = 33.83
dir5 = 34.52
dir6 = 194.92
dir7 = 84.67
dir8 = 79.5
dir9 = 172.65
dir4, dir5, dir6

(33.83, 34.52, 194.92)

Calculation of final disturbances sector

In [14]:
sector1 = [dir1 - alfa1/2, dir1 + alfa1/2]
sector2 = [dir2 - alfa2/2, dir2 + alfa2/2]
sector3 = [dir3 - alfa3/2, dir3 + alfa3/2]
sector4 = [dir4 - alfa4/2, dir4 + alfa4/2]
sector5 = [dir5 - alfa5/2, dir5 + alfa5/2]
sector6 = [dir6 - alfa6/2, dir6 + alfa6/2]
sector7 = [dir7 - alfa7/2, dir7 + alfa7/2]
sector8 = [dir8 - alfa8/2, dir8 + alfa8/2]
sector9 = [dir9 - alfa9/2, dir9 + alfa9/2]

sector1, sector2, sector3, sector4, sector5, sector6, sector7, sector8, sector9

([72.96958073217228, 149.73237976313493],
 [122.39576544885037, 172.54515799448743],
 [150.59208982156204, 215.5677680823571],
 [9.348991664425736, 58.31100833557426],
 [8.119082281327469, 60.92091771867254],
 [183.06132494157083, 206.77867505842914],
 [67.70190643918437, 101.63809356081563],
 [60.253286124990034, 98.74671387500996],
 [160.79132494157085, 184.50867505842916])

In [15]:
final_sector = [float(sector5[0]), float(sector3[1])]
final_sector # not valid sector to discard when using wind directions from 2023-Jan-July csv

[8.119082281327469, 215.5677680823571]

# BEGINNING PART TWO
Import pandas to read csv file and then start the task

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv("2023-Jan-July-Power-data_AS03.csv", parse_dates=['date_time'], dayfirst = True)
df['date_time'] = pd.to_datetime(df['date_time'], dayfirst=True)

df = df.apply(
    lambda col: pd.to_numeric(col, errors='coerce') 
    if col.name != 'date_time' else col
)

df.head()

,date_time,ActPow,ActPow_stdev,ActPow_min,ActPow_max,ROT,ROT_stdev,ROT_min,ROT_max,Pitch,...,yaw,yaw_stdev,Wsp_44m,Wsp_44m_stdev,TI_44m,Wdir_41m,Wdir_41m_stdev,AirAbs_70m,Press_enc_2m,RH_2m
0,2023-01-01 00:00:00,-1.068690,0.764328,-6.3,-0.6,18.4477,1.760370,15.2,20.3,1.32638,...,191.953,8.24550,3.59764,0.266969,7.420661,189.303,5.03607,9.10590,1000.190,99.2582
1,2023-01-01 00:10:00,-1.032230,0.805093,-5.6,-0.6,20.2230,0.042244,20.1,20.3,2.29086,...,184.168,3.24322,4.04453,0.224817,5.558540,188.336,4.32561,9.06290,1000.010,99.2022
2,2023-01-01 00:20:00,-0.980143,0.836413,-8.2,-0.7,20.2212,0.046745,20.0,20.3,2.55750,...,186.459,2.89920,4.26950,0.331550,7.765553,187.380,5.53469,9.05956,999.864,99.1519
3,2023-01-01 00:30:00,-1.309760,1.085390,-8.5,-0.7,20.2236,0.043320,20.1,20.3,2.57907,...,183.715,2.90021,4.32317,0.344980,7.979798,186.668,5.46125,9.05870,999.722,99.1269
4,2023-01-01 00:40:00,14.232000,27.703500,-34.7,134.3,19.4361,1.538740,15.7,22.2,2.19538,...,173.804,1.94374,4.45534,0.453759,10.184614,179.665,4.58699,9.07963,999.615,99.1004


Apply the masks to filter out invalid sector, meaning the exclusion of all the measurements that are within the range of **[8.119082281327469, 215.5677680823571]**

In [18]:
df_filtered = df.copy()

# Remove the waked sector
df_filtered = df_filtered[
    (df_filtered['Wdir_41m'] < 8.119082281327469) | 
    (df_filtered['Wdir_41m'] > 215.5677680823571)
]

# Quick check
print(f"Original data: {len(df)}")
print(f"Filtered data: {len(df_filtered)}")

df_filtered.head()

Original data: 30013
Filtered data: 15882


,date_time,ActPow,ActPow_stdev,ActPow_min,ActPow_max,ROT,ROT_stdev,ROT_min,ROT_max,Pitch,...,yaw,yaw_stdev,Wsp_44m,Wsp_44m_stdev,TI_44m,Wdir_41m,Wdir_41m_stdev,AirAbs_70m,Press_enc_2m,RH_2m
12,2023-01-01 02:00:00,191.247,111.2660,-34.9,458.5,20.7646,3.25070,15.9,26.7,-1.543640,...,220.546,6.101050,6.84244,1.64183,23.994778,226.761,12.10890,10.1724,998.706,99.0432
13,2023-01-01 02:10:00,468.768,170.4060,-12.9,861.9,24.7149,1.90875,18.3,27.2,-0.596077,...,236.208,3.495560,9.88038,1.83196,18.541448,237.586,7.93632,10.7235,998.720,98.9544
14,2023-01-01 02:20:00,364.161,167.4520,97.8,857.6,23.5826,2.03610,19.9,26.6,-1.455890,...,235.258,2.539730,8.72808,1.50427,17.234881,236.811,8.32431,10.6957,998.718,98.5071
15,2023-01-01 02:30:00,131.780,58.5329,-5.8,297.7,19.9583,1.81521,16.3,24.5,-0.968024,...,231.265,3.582970,6.38974,1.11007,17.372677,230.947,8.14356,10.5387,998.780,98.9698
16,2023-01-01 02:40:00,200.082,108.0410,18.0,456.2,20.3644,3.14146,15.8,26.0,-1.540550,...,225.596,0.056075,7.07922,1.90045,26.845515,223.971,8.96407,10.5470,998.809,99.5061


Calculation of density

In [19]:
T = df_filtered['AirAbs_70m'] + 273.15
p = df_filtered['Press_enc_2m'] * 100
phi = df_filtered['RH_2m'] / 100
vap_pressure = 2.05e-6 * np.exp(0.0631846 * T)

R0 = 287.05 # J/(kg*K)
R_W = 461.5 # J/(kg*K)

df_filtered['density'] = 1 / T * (p / R0 - phi * vap_pressure * (1/R0 - 1/R_W))
df_filtered['density']

12       1.227441
13       1.225056
14       1.225177
15       1.225934
16       1.225930
           ...   
29555    1.140401
29556    1.140184
29557    1.140859
29558    1.141583
29559    1.142505
Name: density, Length: 15882, dtype: float64

Since V52 is actively controlled (in fact we have a varying pitch and rotor speed), wind speed will be normalized. Reference air density is assumed to be 1.225 kg/m^3

In [39]:
density_ref = 1.225 # kg/m^3

df_filtered['Wsp_norm'] = df_filtered['Wsp_44m'] * ((density_ref / df_filtered['density']) ** (1/3))
df_filtered['Wsp_norm']

12       6.837902
13       9.880230
14       8.727660
15       6.388117
16       7.077429
           ...   
29555    2.322381
29556    2.298860
29557    2.070371
29558    2.581550
29559    2.399827
Name: Wsp_norm, Length: 15882, dtype: float64

Wind bins creation. Cut-out wind speed is 25 m/s.

In [42]:
bins = np.arange(0.75, 25.25, 0.5) # last wind speed binned is 25 so all velocities up to cut-out ws are included
labels = (bins[:-1] + bins[1:]) / 2 # centers

df_filtered['bin'] = pd.cut(df_filtered['Wsp_norm'], bins=bins, labels=labels)
df_filtered

,date_time,ActPow,ActPow_stdev,ActPow_min,ActPow_max,ROT,ROT_stdev,ROT_min,ROT_max,Pitch,...,TI_44m,Wdir_41m,Wdir_41m_stdev,AirAbs_70m,Press_enc_2m,RH_2m,density,Wsp_norm,bin,Cp
12,2023-01-01 02:00:00,191.24700,111.266000,-34.9,458.5,20.7646,3.250700,15.9,26.7,-1.543640,...,23.994778,226.761000,12.10890,10.1724,998.706,99.0432,1.227441,6.837902,7.0,0.000459
13,2023-01-01 02:10:00,468.76800,170.406000,-12.9,861.9,24.7149,1.908750,18.3,27.2,-0.596077,...,18.541448,237.586000,7.93632,10.7235,998.720,98.9544,1.225056,9.880230,10.0,0.000374
14,2023-01-01 02:20:00,364.16100,167.452000,97.8,857.6,23.5826,2.036100,19.9,26.6,-1.455890,...,17.234881,236.811000,8.32431,10.6957,998.718,98.5071,1.225177,8.727660,8.5,0.000421
15,2023-01-01 02:30:00,131.78000,58.532900,-5.8,297.7,19.9583,1.815210,16.3,24.5,-0.968024,...,17.372677,230.947000,8.14356,10.5387,998.780,98.9698,1.225934,6.388117,6.5,0.000388
16,2023-01-01 02:40:00,200.08200,108.041000,18.0,456.2,20.3644,3.141460,15.8,26.0,-1.540550,...,26.845515,223.971000,8.96407,10.5470,998.809,99.5061,1.225930,7.077429,7.0,0.000434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29555,2023-07-28 19:00:00,-1.26889,0.498421,-6.1,-1.2,13.4962,0.787160,11.8,14.6,0.878057,...,12.832870,4.262190,5.20518,20.2513,960.932,54.6413,1.140401,2.322381,2.5,-0.000084
29556,2023-07-28 19:10:00,-1.25153,0.431182,-6.3,-1.2,11.6622,0.304991,11.1,12.2,0.868169,...,8.119109,3.664000,5.42053,20.2618,960.786,54.9629,1.140184,2.298860,2.5,-0.000085
29557,2023-07-28 19:20:00,-1.26926,0.499176,-5.9,-1.2,11.1039,0.405218,10.4,11.8,0.862699,...,9.906792,358.470000,6.27134,20.1337,960.931,54.9435,1.140859,2.070371,2.0,-0.000118
29558,2023-07-28 19:30:00,-1.25234,0.435768,-5.8,-1.2,12.4439,1.250790,10.7,14.4,0.870932,...,6.955385,0.833448,4.27613,20.0151,961.166,56.9751,1.141583,2.581550,2.5,-0.000060


Statistics calculation per bin.

In [50]:
A = np.pi * (V52diameter / 2) **2   # swept area by blades
df_filtered['Cp'] = df_filtered['ActPow'] / (0.5 * df_filtered['density'] * A * (df_filtered['Wsp_norm']**3))

grouped = df_filtered.groupby('bin')

power_curve = pd.DataFrame({
    'V_mean': grouped['Wsp_norm'].mean(),
    'P_mean': grouped['ActPow'].mean(),
    'P_stdv': grouped['ActPow_stdev'].mean(),
    'Cp': grouped['Cp'].mean(),
    'N': grouped['ActPow'].count()
})
power_curve

C:\Users\user\AppData\Local\Temp\ipykernel_17236\714024119.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df_filtered.groupby('bin')


,V_mean,P_mean,P_stdv,Cp,N
bin,,,,,
1.0,1.041055,-0.629693,0.666406,-4.644875e-04,195
1.5,1.530894,-0.751935,0.690936,-1.682333e-04,352
2.0,2.018408,-0.785879,0.601982,-7.452859e-05,514
2.5,2.508502,-0.872941,0.648767,-4.247452e-05,617
3.0,3.007226,-0.373465,1.550132,-1.303679e-05,589
3.5,3.507978,5.188642,4.839633,8.276972e-05,572
4.0,4.009670,23.191048,13.322917,2.647618e-04,806
4.5,4.489494,43.919593,19.983307,3.642767e-04,850
5.0,4.990921,64.462766,26.398668,3.945807e-04,838
